# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
target 'WRCalendarFortvOS-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	pod 'WRCalendarFortvOS', :path=> '../'	

  # Pods for WRCalendarFortvOS-Example

end
